const ACTIONS = {

    LOGIN: 'LOGIN',
    GET_TOKEN: "GET_TOKEN",
    GET_USER:"GET_USER",
    GET_ALL_USERS:"GET_ALL_USERS",
    GET_ALL_PROJECTS:"GET_ALL_PROJECTS",
    GET_PROJECT:"GET_PROJECT",
    ADD_PROJECT:"ADD_PROJECT",
    GET_REVIEW:"GET_REVIEW",
    GET_ALL_REVIEWS:"GET_ALL_REVIEWS",


}

export default ACTIONS